title: "100 Days Challenge"
email: "YouDontNeedIt@nospam.forever"
description: >-
  This site is an experimental test to find, if a can commit to healthy life for 100 days.
baseurl: ""
url: "https://100dayschallenge.github.io/"
twitter_username:
github_username: "100dayschallenge"

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'
        author: 'nobody'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-paginate
  - jekyll-archives

exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - .idea

jekyll-archives:
  enabled: 'all'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
  layouts:
    year: year-archive
    month: month-archive
    category: tag-archive
    tag: tag-archive
